#! /bin/bash
echo "Números de Fibonacci: 1,1,2,3,5,8,13,21,34,..."
echo ""
num1=0
num2=1
pos=0
clear
while [ $pos -lt 1 ]
do
	printf "Digite a posição até a qual quer imprimir os números = "
	read pos
done
printf "1 "
conta=1
while [ $conta -le $(("$pos" - 1)) ]
do
	((num3 = $num1 + $num2))
	printf "%d " $num3
	num1=$num2
	num2=$num3
        ((conta = $conta + 1))
done
echo ""
echo ""